theme: jekyll-theme-cayman
title: Data Notes
description: My short notes on topics in Data Science, Machine Learning and Statisitcal Analysis
link: Connect with me on [LinkedIn](https://www.linkedin.com/in/sshafei/)
