theme: jekyll-theme-cayman
title: Data Notes
description: My short notes on topics in Data Science, Machine Learning and Statisitcal Analysis
# email address feedback gets sent to
feedback_email: s.shafei@gmail.com
